### PR TITLE
Fix raycast on high density displays

### LINKED ISSUE #223: getIntersectedObjects() sometimes fails to pull the actual objects
Seems like there's something wrong with how mouse coordinates are calculated and passed to the raytracer, because sometimes it returns false positives and other times false negatives.

### PR DESCRIPTION
**Pull request by afonsobspinto**
Closes #223 

https://user-images.githubusercontent.com/19196034/149812610-decff969-2968-4a29-b4c0-16cb6d6f884a.mp4

### CODE REVIEW

File: geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/ThreeDEngine.js [hunk 1]
```diff
@@ -790,32 +788,29 @@ export default class ThreeDEngine {
             }
           }
           this.requestFrame();
-          // this.onSelection(this.selectionStrategy(selectedMap))
```
Comment (afonsobspinto) [inline geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/ThreeDEngine.js:793]: I'm not sure why this was commented out. cc @enicolasgomez
