### PR TITLE
#341 Update trackball controls configs

### LINKED ISSUE #341: Fix canvas simple instances showcase example
It seems to me something is broken in the trackball controls for the simple instances:

From geppetto-showcase in development:
https://user-images.githubusercontent.com/19196034/159042151-b480ec26-1fd1-4c3d-8d19-25a376046ad3.mp4

### PR DESCRIPTION
**Pull request by afonsobspinto**
closes #341

https://user-images.githubusercontent.com/19196034/159065208-05624a24-b2c2-4b94-a211-6f1a7bda3bf1.mp4

### CODE REVIEW

**Review by enicolasgomez — APPROVED** [review]

File: geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/CameraManager.js [hunk 1]
```diff
@@ -58,9 +57,6 @@ export default class CameraManager {
           this.zoomTo(instances);
         }
       }
-      if (rotateSpeed){
```
Comment (afonsobspinto) [inline geppetto.js/geppetto-ui/src/3d-canvas/threeDEngine/CameraManager.js:61]: @afonsobspinto please include this in the other PR
